version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: DPM-backend
    expose:
      - "8080"
    networks:
      - DPM-network
    restart: on-failure

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


  nginx:
    image: nginx:1.27-alpine
    container_name: DPM-nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - DPM-network
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  DPM-network:
    driver: bridge
